language: python
dist: trusty
sudo: false
python:
  - 3.4
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
env:
  global:
    - PIP_INDEX_URL=https://pypi.pacificclimate.org/simple
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - GDALVERSION="2.3.1"
    - CPLUS_INCLUDE_PATH=$GDALINST/include
    - C_INCLUDE_PATH=$GDALINST/include
    - CFLAGS=-I$GDALINST/include

before_install:
  - ./build_gdal.sh
  - "pip install --global-option=build_ext --global-option='-I$GDALINST/include' --global-option='-L$GDALINST/lib' --global-option='-R$GDALINST/lib' GDAL==$GDAL_MINOR_VERSION"
install:
  - pip install -I pytest>=3.0.0
  - pip install -r requirements.txt .
  - pip install .
script:
  - py.test -v ce/tests
