language: python
dist: trusty
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
env:
  global:
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - GDALVERSION="1.11.2"
    - CPLUS_INCLUDE_PATH=$GDALINST/include
    - C_INCLUDE_PATH=$GDALINST/include
    - CFLAGS=-I$GDALINST/include

before_install:
  - mkdir $GDALBUILD
  - mkdir $GDALINST
  - cd $GDALBUILD
  - wget http://download.osgeo.org/gdal/$GDALVERSION/gdal-$GDALVERSION.tar.gz
  - tar -xzf gdal-$GDALVERSION.tar.gz
  - cd gdal-$GDALVERSION
  - ./configure --prefix=$GDALINST
  - make -s -j 2
  - make install
  - cd $TRAVIS_BUILD_DIR
  - export PATH=$GDALINST/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/lib:$LD_LIBRARY_PATH
  - export GDAL_MINOR_VERSION=$(echo $GDALVERSION | sed -e "s/\\.[0-9]\+$//")
  - "pip install --global-option=build_ext --global-option='-I$GDALINST/include' --global-option='-L$GDALINST/lib' --global-option='-R$GDALINST/lib' rasterio GDAL==$GDAL_MINOR_VERSION"
install:
  - pip install -I pytest>=3.0.0
  - pip install -i https://pypi.pacificclimate.org/simple/ .
script:
  - py.test -v ce/tests
  # We only run the ce tests because installing cdo is just too hard: NetCDF support isn't built into the
  # debian cdo pacakges. Once that is resolved (i.e., install the NetCDF support before installing cdo),
  # the following lines can be uncommented to run the data prep tests too.
#  - sudo apt-get install cdo
#  - pip install -i https://pypi.pacificclimate.org/simple/ .[data_prep]
#  - py.test -v dp/tests
