language: python
python:
  - 3.4
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
install:
  - pip install -i http://tools.pacificclimate.org/pypiserver/ --trusted-host tools.pacificclimate.org .
script:
  - py.test -v
