language: python
dist: trusty
sudo: false
python:
  - 3.4
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
env:
  global:
    - PIP_INDEX_URL=https://pypi.pacificclimate.org/simple
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - GDALVERSION="2.3.1"
    - CPLUS_INCLUDE_PATH=$GDALINST/include
    - C_INCLUDE_PATH=$GDALINST/include
    - CFLAGS=-I$GDALINST/include

before_install:
  - mkdir $GDALBUILD
  - mkdir $GDALINST
  - cd $GDALBUILD
  - wget http://download.osgeo.org/gdal/$GDALVERSION/gdal-$GDALVERSION.tar.gz
  - tar -xzf gdal-$GDALVERSION.tar.gz
  - cd gdal-$GDALVERSION
  - ./configure --prefix=$GDALINST
  - make -j 2
  - make install
  - cd $TRAVIS_BUILD_DIR
  - export PATH=$GDALINST/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/lib:$LD_LIBRARY_PATH
  - export GDAL_MINOR_VERSION=$(echo $GDALVERSION | sed -e "s/\\.[0-9]\+$//")
  - "pip install --global-option=build_ext --global-option='-I$GDALINST/include' --global-option='-L$GDALINST/lib' --global-option='-R$GDALINST/lib' GDAL==$GDAL_MINOR_VERSION"
install:
  - pip install -I pytest>=3.0.0
  - pip install -r requirements.txt .
  - pip install .
script:
  - py.test -v ce/tests

