dist: bionic
sudo: false
language: python
python:
  - 3.6
  - 3.7
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
env:
  global:
    - PIP_INDEX_URL=https://pypi.pacificclimate.org/simple
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - GDALVERSION="3.0.4"
    - CPLUS_INCLUDE_PATH=$GDALINST/include
    - C_INCLUDE_PATH=$GDALINST/include
    - CFLAGS=-I$GDALINST/include
cache:
  directories:
    - $GDALINST
    - $GDALBUILD
    - $HOME/.cache/pip
before_install:
  - ./build_gdal.sh
  - export PATH=$GDALINST/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/lib:$LD_LIBRARY_PATH
  - export GDAL_MINOR_VERSION=$(echo $GDALVERSION | sed -e "s/\\.[0-9]\+$//")
  - "pip install --global-option=build_ext --global-option='-I$GDALINST/include' --global-option='-L$GDALINST/lib' --global-option='-R$GDALINST/lib' GDAL==$GDAL_MINOR_VERSION"
install:
  - pip install -r requirements.txt -r test_requirements.txt
  - pip install .
script:
  - python setup.py build_sphinx 
  - py.test -v --flake8
