name: Python CI

on: push

jobs:
  test:

    runs-on: ubuntu-18.04
    container: pcic/geospatial-python:gdal3

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apk add libxml2-dev libxslt-dev
        pip install -U pip wheel
        pip install -i https://pypi.pacificclimate.org/simple -r requirements.txt -r test_requirements.txt
        pip install .
        python setup.py build_sphinx
    - name: Test with pytest (full)
      if: github.ref == 'refs/heads/master'
      run: |
        py.test -v --tb=short --cov --flake8
    - name: Test with pytest (fast)
      if: github.ref != 'refs/heads/master'
      run: |
        py.test -m "not slow" -v --tb=short --flake8
